[project]
name = "pydeps-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = [
    "graphviz>=0.20.3",
    "pydeps>=3.0.1",
]
